// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eaunazzaizmanidgheaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhdW5henphaXptYW5pZGdoZWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Njk5MzgsImV4cCI6MjA2NjU0NTkzOH0.Q3rOqCP4QT3nanQCWogfLyK8HCsuUaDJfBSu5tXLMh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);